packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/*/*'

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  'bcrypt': true
  'esbuild': true
  'less': true
  'lmdb': true
  'msgpackr-extract': true
  'nx': true
  'oxc-resolver': true
  'sharp': true
  'unrs-resolver': true

minimumReleaseAgeExclude:
  - '@nx/angular@22.7.4'
  - '@nx/devkit@22.7.4'
  - '@nx/docker@22.7.4'
  - '@nx/eslint-plugin@22.7.4'
  - '@nx/eslint@22.7.4'
  - '@nx/jest@22.7.4'
  - '@nx/js@22.7.4'
  - '@nx/module-federation@22.7.4'
  - '@nx/nest@22.7.4'
  - '@nx/node@22.7.4'
  - '@nx/nx-darwin-arm64@22.7.4'
  - '@nx/nx-darwin-x64@22.7.4'
  - '@nx/nx-freebsd-x64@22.7.4'
  - '@nx/nx-linux-arm-gnueabihf@22.7.4'
  - '@nx/nx-linux-arm64-gnu@22.7.4'
  - '@nx/nx-linux-arm64-musl@22.7.4'
  - '@nx/nx-linux-x64-gnu@22.7.4'
  - '@nx/nx-linux-x64-musl@22.7.4'
  - '@nx/nx-win32-arm64-msvc@22.7.4'
  - '@nx/nx-win32-x64-msvc@22.7.4'
  - '@nx/rspack@22.7.4'
  - '@nx/web@22.7.4'
  - '@nx/webpack@22.7.4'
  - '@nx/workspace@22.7.4'
  - nx@22.7.4
  - '@nx/angular@23.0.0'
  - '@nx/devkit@23.0.0'
  - '@nx/docker@23.0.0'
  - '@nx/eslint-plugin@23.0.0'
  - '@nx/eslint@23.0.0'
  - '@nx/jest@23.0.0'
  - '@nx/js@23.0.0'
  - '@nx/module-federation@23.0.0'
  - '@nx/nest@23.0.0'
  - '@nx/node@23.0.0'
  - '@nx/nx-darwin-arm64@23.0.0'
  - '@nx/nx-darwin-x64@23.0.0'
  - '@nx/nx-freebsd-x64@23.0.0'
  - '@nx/nx-linux-arm-gnueabihf@23.0.0'
  - '@nx/nx-linux-arm64-gnu@23.0.0'
  - '@nx/nx-linux-arm64-musl@23.0.0'
  - '@nx/nx-linux-x64-gnu@23.0.0'
  - '@nx/nx-linux-x64-musl@23.0.0'
  - '@nx/nx-win32-arm64-msvc@23.0.0'
  - '@nx/nx-win32-x64-msvc@23.0.0'
  - '@nx/rspack@23.0.0'
  - '@nx/web@23.0.0'
  - '@nx/webpack@23.0.0'
  - '@nx/workspace@23.0.0'
  - nx@23.0.0
