// Package handler provides HTTP (HyperText Transfer Protocol) handlers
// for the Sick-Fansubs application.
//
// This package owns the HTTP boundary: it parses incoming requests, applies
// status codes, sets response headers, and encodes JSON bodies. It does not
// own business rules, SQL queries, or database connections.
//
// # Design principles
//
//   - Method-aware [http.ServeMux] patterns (Go 1.22+) — no third-party router.
//   - The request ID is server-generated by middleware.RequestID, and an
//     inbound X-Request-ID header is never trusted (log injection, XSS,
//     collision risk). Handlers mint nothing.
//   - Cache-Control: no-store on health endpoints — stale cached health
//     responses could route traffic to a dead instance.
//   - HealthChecker interface defined at the consuming boundary (the handler
//     package) because the handler is the consumer.
package handler

import (
	"context"
	"net/http"

	"sick-fansubs/internal/logging"
)

// HealthChecker reports whether runtime dependencies are ready to serve traffic.
//
// This is the readiness probe seam. A nil return means "ready"; any error
// means "not ready" and produces a 503 response with {"status":"not_ready"}.
//
// The interface is defined here (the consuming boundary) because the handler
// is what calls Check ([Effective Go: interfaces]). We do not define it in a
// separate "model" or "service" package — that would be a pass-through
// abstraction with no value.
//
// [Effective Go: interfaces]: https://go.dev/doc/effective_go#interfaces
type HealthChecker interface {
	Check(ctx context.Context) error
}

// HealthLive responds to GET /health/live — the liveness probe.
//
// It answers 200 as long as the Go runtime can schedule the handler; it
// never consults a dependency — dependency failure is the readiness probe's
// signal, not a reason to restart the process.
//
// Route: "GET /health/live" (method-aware ServeMux pattern, Go 1.22+).
func HealthLive(w http.ResponseWriter, r *http.Request) {
	logger := logging.From(r.Context())
	writeJSON(w, r, http.StatusOK, map[string]string{"status": "ok"})
	// Probe traffic is high-frequency — success is logged at Debug, not Info,
	// so routine probes don't drown real log signal.
	logger.DebugContext(r.Context(), "health live ok")
}

// HealthReady returns a handler for GET /health/ready.
//
// This is the readiness probe — "is the application ready to serve
// dependency-backed traffic?" It delegates to a HealthChecker; if the
// checker reports an error, the response is 503 with {"status":"not_ready"}.
//
// We return a [http.HandlerFunc] closure so that the checker dependency is
// captured at wiring time in main.go, not stored in a global variable. This
// makes the handler testable: tests can inject a failing checker without
// touching global state.
//
// Route: "GET /health/ready" (method-aware ServeMux pattern, Go 1.22+).
// The response contract is in docs/api/openapi.yaml (paths./health/ready).
func HealthReady(checker HealthChecker) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		logger := logging.From(r.Context())
		if err := checker.Check(r.Context()); err != nil {
			writeJSON(w, r, http.StatusServiceUnavailable, map[string]string{"status": "not_ready"})
			logger.WarnContext(r.Context(), "readiness check failed", "error", err)
			return
		}
		writeJSON(w, r, http.StatusOK, map[string]string{"status": "ready"})
		logger.DebugContext(r.Context(), "health ready ok")
	}
}
